### ISSUE TITLE
3. core motion 리서치 

### ISSUE THREAD

**Issue by lucid2713** [ProjectInTheClass/MinApp#4]
자이로센서 등으로 움직임에 적용할 
core motion 리서치, 적용하면 좋을것 추천

**Comment by shhan826** [comment]
- 코어모션 사용해서 간단하게 움직임 값 가져오기 튜토리얼
https://www.youtube.com/watch?v=O68O7yUK_9c
- 코어모션 공식 설명 페이지
https://developer.apple.com/reference/coremotion
- 실제로 코어모션을 활용해서 앱 만드는 대학 강좌
https://www.youtube.com/watch?v=H9dOfrzlPrE
